### ISSUE TITLE
老哥你的readme该更新了

### ISSUE THREAD

**Issue by ChowRex** [htve/GitlabForChinese#3]
某一版本更新后可能取消掉了9.2.0的文件，现在执行readme的命令不可用了
修改 第10步的ii为
cd /tmp && wget https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/yum/el7/gitlab-ce-9.2.2-ce.0.el7.x86_64.rpm
rpm -i gitlab-ce-9.2.2-*.rpm
修改 第12步为
cd /opt && curl -LJO https://github.com/htve/GitlabForChinese/releases/download/v9.2.2.zh/v9.2.2.zh1.diff
patch -d /opt/gitlab/embedded/service/gitlab-rails -p1 < v9.2.2.*.diff

这样就OK了

**Comment by htve** [comment]
@ChowRex 最近在忙于 gitlab的官方I18N工作,在这几天将发布的gitlab 10.0 中. 你将看到部分i18n.

**Comment by htve** [comment]
在gitlab 10.0 时,我会更新一下readme的文件的

**Comment by ChowRex** [comment]
@htve 老哥，有个严重问题，第十三步 cd /opt/gitlab/embedded/service/gitlab-rails && bundle install --deployment --without development test mysql aws kerberos
 这步 烦请更新为
cd /opt/gitlab/embedded/service/gitlab-rails && bundle lock --update=omniauth-google-oauth2 && bundle install --deployment --without development test mysql aws kerberos

否则无法继续，报错
Downloading omniauth-google-oauth2-0.4.1 revealed dependencies not in the API or the lockfile (omniauth-oauth2 (>= 1.3.1), jwt (~> 1.5.2)).
Either installing with `--full-index` or running `bundle update omniauth-google-oauth2` should fix the problem.
并且 执行提示方案并不能修复这个错误

**Comment by htve** [comment]
已解决
